const symptoms = [
    "Fever",
    "Coughing",
    "Nausea",
    "Sore Throat",
    "Chills",
    "Diarrhea",
    "Fatigue",
    "Loss of Appetite",
    "Loss of Smell",
    "Loss of Taste",
    "Poor Vision",
    "Blindness",
    "Deafness",
    "Dizziness",
    "Memory Loss",
    "Ulcers",
    "Asthma",
]